version: '3.9'
name: nginx-php-fpm-db

services:
    web:
        image: nginx:latest
        ports:
            - '80:80'
        environment:
            - LOCAL_DOMAIN=transfer-corp.test
            - LIVE_DOMAIN=transfer-solutions.com
        volumes:
            - ../:/var/www/html
            - ./logs/nginx:/logs/nginx
            - ./config/nginx:/etc/nginx/templates
        depends_on:
            - php-fpm
        links:
            - php-fpm
            - db
    php-fpm:
        build: php-fpm/7.4
        volumes:
            - ../:/var/www/html
            - ./logs/xdebug:/logs/xdebug
            - ./config/php/custom.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
            - ./config/php/php-override.ini:/usr/local/etc/php/conf.d/zz-php-override.ini
            - ./logs/php-fpm/:/tmp/xdebug_log
        links:
            - db
    db:
        image: mariadb:latest
        environment:
            MARIADB_DATABASE: transfercorp
            MARIADB_USER: transfercorp
            MARIADB_PASSWORD: transfercorp
            MARIADB_ROOT_PASSWORD: root
        ports:
            - "3336:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d


